version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
  mongo:
    image: mongo
  railsvm:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - MONGO_HOST=mongo:27017
  rake:
      build: .
      command: docker/docker-rake-commands.sh
      volumes:
        - .:/myapp
      depends_on:
        - postgres
        - mongo
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD
        - MONGO_HOST=mongo:27017
  test:
      build: .
      command: docker/docker-test-commands.sh
      volumes:
        - .:/myapp
      depends_on:
        - postgres
        - mongo
      ports:
        - "5900:5900"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD
        - MONGO_HOST=mongo:27017
        - VNC_PASSWORD=password
